# Site settings
title: Си-плекс
email: contact@c-plex.ru
description: > # this means to ignore newlines until "baseurl:"
  Компания &laquo;Си-плекс&raquo; разрабатывает:<ul>
    <li>мобильные приложения;</li>
    <li>вэб-приложения;</li>
    <li>приложения для настольных систем.</li>
  </ul>
url: "http://c-plex.ru" # the base hostname & protocol for your site

navigation:
- text: Проекты
  url: /projects/
- text: Контакты
  url: /contacts/

collections:
  projects:
    output: true
    permalink: /project/:path/

# Build settings
highlighter: pygments #true
markdown: kramdown
permalink: pretty
